version: '3'
services:
  # Load Balancer
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "4000:80"
    depends_on:
      - app1
      - app2
      - app3

  # Replica 1
  app1:
    image: stock-ingestor
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  # Replica 2
  app2:
    image: stock-ingestor
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  # Replica 3
  app3:
    image: stock-ingestor
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M